version: "3.7"
services:
  nats:
    image: nats:2.9.21
    container_name: 'nats'
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-c /etc/nats/nats.conf"
    volumes:
      - ./:/etc/nats
    networks:
      - nats

networks:
  nats:
    name: nats
