# CI du microservice map

.map_service_variables:
  variables:
    # Chemin vers le répertoire du service depuis le backend
    SERVICE_FOLDER: "microservices/map"
    # Nom qui sera donné à l'image Docker du service
    SERVICE_IMAGE_NAME: "backend/multi-map"
    # Nom du service pour le déclenchement manuel dans GitLab
    CI_SERVICE_NAME: "map"

include:
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/templates-ci.yml'

build-service-map:
  extends:
    - .map_service_variables
    - .template_build_microservice
    - .microservice_rules_template
  stage: build-package

deploy-service-map:
  extends:
    - .map_service_variables
    - .template_docker_deploy_microservice
    - .microservice_rules_template
  stage: build-deploy-docker
  needs:
    - job: build-service-map
      artifacts: true
