# CI du microservice clocking
backend:microservice:clocking:
  stage: packages
  needs:
    - check-nodejs-version
  variables:
    NODE_VERSION: $NODE_VERSION
  trigger:
    include: ${BACKEND_PATH}/microservices/clocking/.gitlab-ci.yml
    strategy: depend
  rules:
    # On ne déclenche ce job que lorsqu'il y a eu du changement au niveau de backend/microservices/clocking
    - changes:
        - ${BACKEND_PATH}/microservices/clocking/**/*
