# CI du microservice social-network
backend:microservice:social-network:
  stage: packages
  needs:
    - check-nodejs-version
  variables:
    NODE_VERSION: $NODE_VERSION
  trigger:
    include: ${BACKEND_PATH}/microservices/social-network/.gitlab-ci.yml
    strategy: depend
  rules:
    # On ne déclenche ce job que lorsqu'il y a eu du changement au niveau de backend/microservices/social-network
    - if: '$CI_COMMIT_BRANCH == "develop-sied"'
      changes:
        - ${BACKEND_PATH}/microservices/social-network/**/*
