services:

  wordpress-db:
    container_name: wordpress-db
    image: bitnami/mariadb:latest
    volumes:
      - ./wp-data/mariadb_data:/bitnami/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
    ports:
      - '3306:3306'
    networks:
      - wordpress-network

  wordpress:
    container_name: wordpress
    image: bitnami/wordpress:latest
    restart: unless-stopped
    ports:
      - '9090:8080'
    networks:
      - wordpress-network
    environment:
      # Variables spécifiques à Bitnami WordPress
      WORDPRESS_BLOG_NAME: "Mon Blog"
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: password
      WORDPRESS_EMAIL: admin@example.com
      WORDPRESS_BLOG_URL: http://localhost:9090
      WORDPRESS_SKIP_INSTALL: ${WORDPRESS_SKIP_INSTALL:-no}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_INSTALL_LOCALE: 'fr_FR' # Propre au script init-wordpress.sh

      # Connexion à la base de données
      WORDPRESS_DATABASE_HOST: wordpress-db
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
      WORDPRESS_DATABASE_NAME: wordpress

      # Variables supplémentaires
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT: |
        define('WP_ENVIRONMENT_TYPE', 'local');
        define('WP_DEBUG_DISPLAY', false);

      # Sécurité supplémentaire avec un serveur proxy Nginx
#      NGINX_UPLOADS_PROXY: 'http://localhost:8080'
#      WORDPRESS_HTACCESS_OVERRIDE_NONE: no
#      WORDPRESS_ENABLE_HTACCESS_PERSISTENCE: yes

    volumes:
      - ./wp-data/wordpress_data:/bitnami/wordpress
      - ./docker-entrypoint-init.d:/docker-entrypoint-init.d:ro
#      - ./wp-data/uploads:/var/www/html/wp-content/uploads # Ne pas monter directement dans /opt/bitnami/wordpress/wp-content/ car sinon l'init de l'image tombe en erreur
    depends_on:
      - wordpress-db

#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    ports:
#      - '8080:80'
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./wp-data/uploads:/var/www/html/wp-content/uploads:ro
#    networks:
#      - wordpress-network
#    depends_on:
#      - wordpress

networks:
  wordpress-network:
