variables:
  # Chemin vers le backend
  BACKEND_PATH: 'dev/user-backend-nest'
  # Chemin vers les connecteurs
  CONNECTORS_PATH: 'dev/connectors'
  # Chemin vers le frontend
  FRONTEND_PATH: 'dev/user-frontend-ionic'

stages:
  - build-package
  - build-deploy-docker

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - '${CI_PROJECT_DIR}/.pnpm-store'
  policy: pull-push

before_script:
  - npm install --global corepack@latest
  - corepack enable
  - corepack prepare pnpm@latest-10 --activate
  - pnpm config set store-dir .pnpm-store

workflow:
  # La pipeline ne se déclenchera que si les modifications ont eu lieu sur les branches suivantes
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "preprod" || $CI_COMMIT_BRANCH == "develop"'

include:
  # CI backend
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/auth.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/cards.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/chatbot.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/clocking.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/contact-us.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/contacts.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/features.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/important-news.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/mail-calendar.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/main.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/map.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/notifications.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/restaurants.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/rss.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/schedule.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/social-network.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/static-pages.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/backend/statistics.gitlab-ci.yml'
  # CI connecteurs
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/connectors/cms-connector.gitlab-ci.yml'
  # CI frontend
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/frontend/pwa-dev.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/frontend/pwa-preprod.gitlab-ci.yml'
  - local: '${CI_PROJECT_DIR}/ci-config/gitlab-example/frontend/pwa-prod.gitlab-ci.yml'
