export default () => ({
  cmsName: 'Directus',
  apiUrl: process.env.DIRECTUS_API_URL || 'http://localhost:8055',
  apiToken: process.env.DIRECTUS_API_TOKEN || '',
  timeout: 5000,
  // assetsPath: '/assets',
  // channelsPath: '/items/channels',
  // contactUsPath: '/items/contact_us',
  // featuresPath: '/items/features',
  // languagesPath: '/items/languages',
  // loginPath: '/items/login',
  // importantNewsPath: '/items/important_news',
  // pagesPath: '/items/pages',
  // socialNetworksPath: '/items/social_networks',
  // widgetsPath: '/items/widgets',
  // fields: '?fields[]=*',
  // fieldsTranslations: ',translations.*',
  // fieldsAuthorization: ',authorization.*',
});
